### ISSUE TITLE
It generates index file without ".html" extension.

### ISSUE THREAD

**Issue by soyme** [midnightSuyama/jekyll-paginate-category#2]
Hello. Thank you for your plugin.
I have installed this plugin on my jekyll. But there is some problem.
I expected that it generates `index.html`, but `index` is generated without any extension.

Could you help me about this problem? Thanks.

**Comment by bazhenovn** [comment]
Здравствуйте, я думаю вы ошиблись. Я не создавал не каких плагинов.

**Comment by Neo-Oli** [comment]
Can this be reopened? This is definitely still an issue.

**Comment by midnightSuyama** [comment]
Confirmed in jekyll v3.1.2, And fixed v0.1.1.
Thanks!

**Comment by fantasie** [comment]
Oh, thanks. I reopened this issue.

**Comment by soyme** [comment]
Now I have confirmed that this issue is fixed in v0.1.1. Thanks 😊
