### ISSUE TITLE
multiple categories support?

### ISSUE THREAD

**Issue by naffan2014** [midnightSuyama/jekyll-paginate-category#6]
i have a lot of categories, like life,thinking,economy and so on.
is this plugin could generate different categories  by  paginatoin_dir: "life,thinking,economy"?

**Comment by naffan2014** [comment]
from reading your .rb, i think it cannot meet my need. right?

**Comment by midnightSuyama** [comment]
@naffan2014 If the categories are `life,thinking,economy`, it belongs to `life`, `thinking` and `economy` directory.

**Comment by naffan2014** [comment]
still can't get it . could you give me a multiple categories example?thank you

**Comment by midnightSuyama** [comment]
@naffan2014 Did you use comma-separated by any chance? Categories (plural key) can be specified as a YAML list or a space-separated string. [See also](https://jekyllrb.com/docs/frontmatter/#predefined-variables-for-posts).

## Example (space-separated)

```
---
layout: post
title: Example
date: 2017-04-12 00:00:00
categories: life thinking economy
---
```

**Comment by naffan2014** [comment]
> my jekyll version is 3.3.1

Oh,no. sorry i make you misunderstanding.  i mean life,thinking,economy have no relation. 
for example,i  have  three category.one is life  one is thinking  one is economy.
when i write post want to put it in life , i will use 
```
---
title: today i meet alot of friends
categories: life
excerpt: this is description
---
```

and when i write some thinking posts, i will use
```
---
title: why jekyll use ruby
categories: thinking
excerpt: this is description
---
```

and then, when i write some economy posts,i will use

```
---
title: nowadays economy
categories: economy
excerpt: this is description
---
```

when i done writing, then run `jekyll serve`. the "today i meet alot of friends" will be arranged into life document, the "why jekyll use ruby" will go into thinking document, and the "nowadays economy" will be in economy document.

my question is :  all articles belong to post. i can only get pagination on my all articles. but i want to get every category pagination. can your plugin support it?

**Comment by naffan2014** [comment]
i think my question is the same as #3, maybe your plugin cannot support it
