### ISSUE TITLE
Newbie comments

### ISSUE THREAD

**Issue by dannykennedy** [midnightSuyama/jekyll-paginate-category#7]
Hi @midnightSuyama , thanks for this great plugin. 

I got it working, but it was a little harder than it should have been because I didn't really understand the basics at first. I think it would be good to add a comment like below to the README (I tried doing a pull request but no permissions)

## Simple how-to

This plugin is designed to generate paginated categories for your jekyll project. If you've added categories to the YAML front matter for your posts, the only files you should need to change are your _config.yml and index.html files. 

Change these files as indicated below, then build your project. A set of paginated category pages will be generated in your _site folder, in the folder you specify in category_dir. The structure of these will be based on your index.html file, and the page.title for each will be the name of the category. These will then be accessible at e.g. myblog.com/categories/mycategory.

**Comment by midnightSuyama** [comment]
@dannykennedy Thanks! Merged.
